# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: nightly-2016-08-17

# Local packages, usually specified by relative directory name
packages:
- '.'
- 'submodules/binary-serialise-cbor'
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- typesafe-endian-0.1.0.1
allow-newer: true
